name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 下载架构编译配置文件
      run: |
        mkdir -p ./${{ matrix.ARCHITECTURE }}
    - name: Download files
      run: |
        wget -O  ./rk33xx/feeds.conf https://fw0.koolcenter.com/iStoreOS/r2s/feeds.conf
        wget -O  ./rk33xx/.config https://fw0.koolcenter.com/iStoreOS/r2s/config.buildinfo

        wget -O ./rk35xx/feeds.conf https://fw0.koolcenter.com/iStoreOS/h88k/feeds.conf
        wget -O ./rk35xx/.config https://fw0.koolcenter.com/iStoreOS/h88k/config.buildinfo

        wget -O ./x86/feeds.conf https://fw0.koolcenter.com/iStoreOS/x86_64_efi/feeds.conf
        wget -O ./x86/.config https://fw0.koolcenter.com/iStoreOS/x86_64_efi/config.buildinfo

    - name: 同步配置
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        keep_minimum_runs: 1
        token: ${{ secrets.ACCESS_TOKEN }}